apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: devops
spec:
  project: default
  source:
    repoURL: 'https://github.com/juanferrla/helm-charts.git'
    targetRevision: HEAD
    path: argo-cd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://github.com/juanferrla/helm-charts.git'
      targetRevision: HEAD
      path: argo-cd
      helm:
        valueFiles:
          - values.yaml


