apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: flask
    repoURL: https://github.com/juanferrla/helm-charts.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground



