apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-and-push-docker-
spec:
  entrypoint: build-push
  templates:
  - name: build-push
    steps:
    - - name: clone-repo
        template: git-clone
    - - name: build-docker-image
        template: docker-build
    - - name: push-image
        template: docker-push

  # Template para clonar el repositorio Git
  - name: git-clone
    container:
      image: alpine/git:latest
      command: [sh, -c]
      args:
        - |
        git clone https://github.com/juanferrla/kappa.git /src;
      volumeMounts:
        - name: workspace
          mountPath: /src

  # Template para construir la imagen Docker
  - name: docker-build
    container:
      image: docker:latest
      command: [sh, -c]
      args:
        - docker build -t my-mssql /src/mssql/.

  # Template para subir la imagen a Harbor
  - name: docker-push
    container:
      image: docker:latest
      command: [sh, -c]
      args:
        - echo "$DOCKER_PASSWORD" | docker login harbor.juanan.local -u "$DOCKER_USERNAME" --password-stdin;
          docker push harbor.juanan.local/default/my-mssql:latest
      env:
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: docker-secret
              key: admin
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-secret
              key: Admin123

  volumes:
  - name: workspace
    emptyDir: {}
  # Volumen para interactuar con Docker
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
    # Volumen para la configuración del daemon.json
  - name: daemon-config
    configMap:
      name: docker-config
