apiVersion: v2
appVersion: 0.15.0
dependencies:
- condition: datahub-gms.enabled
  name: datahub-gms
  repository: file://./subcharts/datahub-gms
  version: 0.2.177
- condition: datahub-frontend.enabled
  name: datahub-frontend
  repository: file://./subcharts/datahub-frontend
  version: 0.2.161
- condition: global.datahub_standalone_consumers_enabled
  name: datahub-mae-consumer
  repository: file://./subcharts/datahub-mae-consumer
  version: 0.2.163
- condition: global.datahub_standalone_consumers_enabled
  name: datahub-mce-consumer
  repository: file://./subcharts/datahub-mce-consumer
  version: 0.2.168
- condition: datahub-ingestion-cron.enabled
  name: datahub-ingestion-cron
  repository: file://./subcharts/datahub-ingestion-cron
  version: 0.2.146
- condition: acryl-datahub-actions.enabled
  name: acryl-datahub-actions
  repository: file://./subcharts/acryl-datahub-actions
  version: 0.2.149
description: A Helm chart for DataHub
maintainers:
- email: datahub@acryl.io
  name: DataHub
name: datahub
type: application
version: 0.5.6
